# Copyright (C) 2017-2020 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lenovo/karate/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/lenovo/karate

PRODUCT_COPY_FILES += \
    vendor/lenovo/karate/proprietary/vendor/etc/acdbdata/msm8937-karate-snd-card/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/msm8937-karate-snd-card/Bluetooth_cal.acdb \
    vendor/lenovo/karate/proprietary/vendor/etc/acdbdata/msm8937-karate-snd-card/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/msm8937-karate-snd-card/General_cal.acdb \
    vendor/lenovo/karate/proprietary/vendor/etc/acdbdata/msm8937-karate-snd-card/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/msm8937-karate-snd-card/Global_cal.acdb \
    vendor/lenovo/karate/proprietary/vendor/etc/acdbdata/msm8937-karate-snd-card/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/msm8937-karate-snd-card/Handset_cal.acdb \
    vendor/lenovo/karate/proprietary/vendor/etc/acdbdata/msm8937-karate-snd-card/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/msm8937-karate-snd-card/Hdmi_cal.acdb \
    vendor/lenovo/karate/proprietary/vendor/etc/acdbdata/msm8937-karate-snd-card/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/msm8937-karate-snd-card/Headset_cal.acdb \
    vendor/lenovo/karate/proprietary/vendor/etc/acdbdata/msm8937-karate-snd-card/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/msm8937-karate-snd-card/Speaker_cal.acdb \
    vendor/lenovo/karate/proprietary/vendor/lib/libactuator_dw9767_karateof.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9767_karateof.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libactuator_dw9767_karateqt.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9767_karateqt.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateof_a3_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateof_a3_default_preview.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateof_a3_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateof_a3_default_video.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateof_a3_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateof_a3_hfr_120.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateof_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateof_common.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateof_cpp_ds_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateof_cpp_ds_chromatix.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateof_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateof_cpp_hfr_120.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateof_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateof_cpp_liveshot.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateof_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateof_cpp_preview.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateof_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateof_cpp_snapshot.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateof_cpp_us_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateof_cpp_us_chromatix.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateof_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateof_cpp_video.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateof_cpp_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateof_cpp_video_full.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateof_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateof_default_video.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateof_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateof_hfr_120.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateof_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateof_postproc.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateof_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateof_preview.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateof_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateof_snapshot.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateof_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateof_video_full.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateof_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateof_zsl_preview.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateof_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateof_zsl_video.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateqt_a3_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateqt_a3_default_preview.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateqt_a3_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateqt_a3_default_video.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateqt_a3_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateqt_a3_hfr_120.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateqt_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateqt_common.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateqt_cpp_ds_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateqt_cpp_ds_chromatix.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateqt_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateqt_cpp_hfr_120.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateqt_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateqt_cpp_liveshot.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateqt_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateqt_cpp_preview.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateqt_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateqt_cpp_snapshot.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateqt_cpp_us_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateqt_cpp_us_chromatix.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateqt_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateqt_cpp_video.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateqt_cpp_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateqt_cpp_video_full.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateqt_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateqt_default_video.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateqt_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateqt_hfr_120.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateqt_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateqt_postproc.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateqt_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateqt_preview.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateqt_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateqt_snapshot.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateqt_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateqt_video_full.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateqt_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateqt_zsl_preview.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx219_karateqt_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karateqt_zsl_video.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateof_4k_preview_dw9767.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateof_4k_preview_dw9767.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateof_4k_video_dw9767.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateof_4k_video_dw9767.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateof_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateof_common.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateof_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateof_cpp_hfr_120.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateof_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateof_cpp_liveshot.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateof_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateof_cpp_preview.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateof_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateof_cpp_snapshot.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateof_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateof_cpp_video.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateof_cpp_video_4k.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateof_cpp_video_4k.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateof_default_preview_dw9767.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateof_default_preview_dw9767.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateof_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateof_default_video.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateof_default_video_dw9767.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateof_default_video_dw9767.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateof_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateof_hfr_120.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateof_hfr_120_dw9767.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateof_hfr_120_dw9767.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateof_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateof_postproc.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateof_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateof_preview.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateof_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateof_snapshot.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateof_video_4k.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateof_video_4k.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateof_zsl_preview_dw9767.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateof_zsl_preview_dw9767.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateof_zsl_video_dw9767.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateof_zsl_video_dw9767.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateqt_4k_preview_dw9767.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateqt_4k_preview_dw9767.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateqt_4k_video_dw9767.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateqt_4k_video_dw9767.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateqt_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateqt_common.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateqt_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateqt_cpp_hfr_120.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateqt_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateqt_cpp_liveshot.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateqt_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateqt_cpp_preview.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateqt_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateqt_cpp_snapshot.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateqt_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateqt_cpp_video.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateqt_cpp_video_4k.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateqt_cpp_video_4k.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateqt_default_preview_dw9767.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateqt_default_preview_dw9767.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateqt_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateqt_default_video.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateqt_default_video_dw9767.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateqt_default_video_dw9767.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateqt_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateqt_hfr_120.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateqt_hfr_120_dw9767.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateqt_hfr_120_dw9767.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateqt_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateqt_postproc.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateqt_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateqt_preview.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateqt_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateqt_snapshot.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateqt_video_4k.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateqt_video_4k.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateqt_zsl_preview_dw9767.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateqt_zsl_preview_dw9767.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libchromatix_imx258_karateqt_zsl_video_dw9767.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx258_karateqt_zsl_video_dw9767.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_modules.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libmmcamera_dw9767_karateof_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_dw9767_karateof_eeprom.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libmmcamera_dw9767_karateqt_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_dw9767_karateqt_eeprom.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libmmcamera_imx219_karateof_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx219_karateof_eeprom.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libmmcamera_imx219_karateqt_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx219_karateqt_eeprom.so \
    vendor/lenovo/karate/proprietary/vendor/lib/libmmcamera_imx258.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx258.so

PRODUCT_PACKAGES += \
    qdcm_calib_data_ili7807d_1080p_video_YAS \
    qdcm_calib_data_ili7807d_2nd_1080p_video_YAS \
    qdcm_calib_data_otm1901a_1080p_video_TianMa \
    qdcm_calib_data_otm1901a_1080p_video_TianMa_G6
