# Copyright (C) 2017-2018 The LineageOS Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/lenovo/karatep/setup-makefiles.sh

PRODUCT_COPY_FILES += \
    vendor/lenovo/karatep/proprietary/vendor/acdb/msm8937-karatep-snd-card/Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/acdb/msm8937-karatep-snd-card/Bluetooth_cal.acdb \
    vendor/lenovo/karatep/proprietary/vendor/acdb/msm8937-karatep-snd-card/General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/acdb/msm8937-karatep-snd-card/General_cal.acdb \
    vendor/lenovo/karatep/proprietary/vendor/acdb/msm8937-karatep-snd-card/Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/acdb/msm8937-karatep-snd-card/Global_cal.acdb \
    vendor/lenovo/karatep/proprietary/vendor/acdb/msm8937-karatep-snd-card/Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/acdb/msm8937-karatep-snd-card/Handset_cal.acdb \
    vendor/lenovo/karatep/proprietary/vendor/acdb/msm8937-karatep-snd-card/Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/acdb/msm8937-karatep-snd-card/Hdmi_cal.acdb \
    vendor/lenovo/karatep/proprietary/vendor/acdb/msm8937-karatep-snd-card/Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/acdb/msm8937-karatep-snd-card/Headset_cal.acdb \
    vendor/lenovo/karatep/proprietary/vendor/acdb/msm8937-karatep-snd-card/Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/acdb/msm8937-karatep-snd-card/Speaker_cal.acdb \
    vendor/lenovo/karatep/proprietary/vendor/lib/libactuator_dw9767_karatepof.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9767_karatepof.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libactuator_dw9767_karatepsy.so:$(TARGET_COPY_OUT_VENDOR)/lib/libactuator_dw9767_karatepsy.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepof_a3_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepof_a3_default_preview.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepof_a3_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepof_a3_default_video.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepof_a3_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepof_a3_hfr_120.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepof_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepof_common.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepof_cpp_ds_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepof_cpp_ds_chromatix.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepof_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepof_cpp_hfr_120.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepof_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepof_cpp_liveshot.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepof_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepof_cpp_preview.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepof_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepof_cpp_snapshot.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepof_cpp_us_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepof_cpp_us_chromatix.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepof_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepof_cpp_video.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepof_cpp_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepof_cpp_video_full.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepof_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepof_default_video.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepof_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepof_hfr_120.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepof_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepof_postproc.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepof_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepof_preview.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepof_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepof_snapshot.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepof_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepof_video_full.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepof_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepof_zsl_preview.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepof_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepof_zsl_video.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepqt_a3_default_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepqt_a3_default_preview.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepqt_a3_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepqt_a3_default_video.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepqt_a3_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepqt_a3_hfr_120.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepqt_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepqt_common.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepqt_cpp_ds_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepqt_cpp_ds_chromatix.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepqt_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepqt_cpp_hfr_120.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepqt_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepqt_cpp_liveshot.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepqt_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepqt_cpp_preview.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepqt_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepqt_cpp_snapshot.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepqt_cpp_us_chromatix.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepqt_cpp_us_chromatix.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepqt_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepqt_cpp_video.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepqt_cpp_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepqt_cpp_video_full.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepqt_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepqt_default_video.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepqt_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepqt_hfr_120.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepqt_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepqt_postproc.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepqt_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepqt_preview.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepqt_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepqt_snapshot.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepqt_video_full.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepqt_video_full.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepqt_zsl_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepqt_zsl_preview.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_imx219_karatepqt_zsl_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_imx219_karatepqt_zsl_video.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_common.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_cpp_hfr_120.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_cpp_hfr_60.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_cpp_hfr_90.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_cpp_liveshot.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_cpp_preview.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_cpp_snapshot.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_cpp_video.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_default_preview_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_default_preview_dw9800.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_default_video.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_default_video_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_default_video_dw9800.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_hfr_120.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_hfr_120_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_hfr_120_dw9800.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_hfr_60.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_hfr_60_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_hfr_60_dw9800.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_hfr_90.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_hfr_90_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_hfr_90_dw9800.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_postproc.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_preview.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_snapshot.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_zsl_preview_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_zsl_preview_dw9800.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepof_zsl_video_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepof_zsl_video_dw9800.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_common.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_common.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_cpp_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_cpp_hfr_120.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_cpp_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_cpp_hfr_60.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_cpp_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_cpp_hfr_90.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_cpp_liveshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_cpp_liveshot.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_cpp_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_cpp_preview.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_cpp_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_cpp_snapshot.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_cpp_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_cpp_video.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_default_preview_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_default_preview_dw9800.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_default_video.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_default_video.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_default_video_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_default_video_dw9800.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_hfr_120.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_hfr_120.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_hfr_120_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_hfr_120_dw9800.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_hfr_60.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_hfr_60.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_hfr_60_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_hfr_60_dw9800.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_hfr_90.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_hfr_90.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_hfr_90_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_hfr_90_dw9800.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_postproc.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_postproc.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_preview.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_preview.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_snapshot.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_snapshot.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_zsl_preview_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_zsl_preview_dw9800.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libchromatix_s5k3p3_karatepsy_zsl_video_dw9800.so:$(TARGET_COPY_OUT_VENDOR)/lib/libchromatix_s5k3p3_karatepsy_zsl_video_dw9800.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libmmcamera2_sensor_modules.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera2_sensor_modules.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libmmcamera_dw9767_karatepof_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_dw9767_karatepof_eeprom.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libmmcamera_dw9767_karatepsy_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_dw9767_karatepsy_eeprom.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libmmcamera_imx219_karatepof_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx219_karatepof_eeprom.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libmmcamera_imx219_karatepqt_eeprom.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_imx219_karatepqt_eeprom.so \
    vendor/lenovo/karatep/proprietary/vendor/lib/libmmcamera_s5k3p3.so:$(TARGET_COPY_OUT_VENDOR)/lib/libmmcamera_s5k3p3.so

PRODUCT_PACKAGES += \
    qdcm_calib_data_hx8399c_1080p_video_tm \
    qdcm_calib_data_ili7807d_1080p_video_DJN \
    qdcm_calib_data_nt35596_1080p_video_tm
